from io import BytesIO

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt


def create_docx(document_text: str, document_type: str = "Legal Document") -> bytes:
    """
    Create a DOCX file from generated legal document text.
    """

    document = Document()

    # Default font
    styles = document.styles
    styles["Normal"].font.name = "Times New Roman"
    styles["Normal"].font.size = Pt(11)

    # Title
    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    title_run = title.add_run(document_type)
    title_run.bold = True
    title_run.font.name = "Times New Roman"
    title_run.font.size = Pt(16)

    # Document content
    for line in document_text.splitlines():

        line = line.strip()

        if not line:
            document.add_paragraph()
            continue

        # Heading-like lines
        if (
            line.isupper()
            or line.startswith("SECTION ")
            or line.startswith("ARTICLE ")
        ):
            paragraph = document.add_paragraph()
            run = paragraph.add_run(line)
            run.bold = True
            run.font.name = "Times New Roman"
            run.font.size = Pt(12)

        else:
            paragraph = document.add_paragraph()
            run = paragraph.add_run(line)
            run.font.name = "Times New Roman"
            run.font.size = Pt(11)

    # Footer
    section = document.sections[0]
    footer = section.footer

    footer_paragraph = footer.paragraphs[0]
    footer_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_run = footer_paragraph.add_run(
        "Generated by LegalEase AI. "
        "This document is an AI-generated draft and should be reviewed by a qualified legal professional."
    )

    footer_run.font.name = "Times New Roman"
    footer_run.font.size = Pt(8)

    # Save to memory
    output = BytesIO()
    document.save(output)
    output.seek(0)

    return output.getvalue()