import html


def create_html_preview(document_text: str) -> str:
    """Create an HTML preview of the generated legal document."""

    escaped_text = html.escape(document_text)

    return f"""
    <div style="
        background-color: white;
        color: #222;
        padding: 30px;
        border-radius: 10px;
        border: 1px solid #ddd;
        font-family: 'Times New Roman', serif;
        line-height: 1.7;
    ">
        <h2 style="text-align:center;">Legal Document Preview</h2>

        <div style="
            white-space: pre-wrap;
            font-size: 16px;
        ">
{escaped_text}
        </div>

        <hr>

        <p style="
            text-align:center;
            font-size:12px;
            color:#777;
        ">
            Generated by LegalEase AI.
            This is an AI-generated draft and should be reviewed
            by a qualified legal professional.
        </p>
    </div>
    """