from io import BytesIO

from fpdf import FPDF


def create_pdf(document_text: str, document_type: str = "Legal Document") -> bytes:
    """Create a PDF file from the generated legal document."""

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Times", "B", 16)
    pdf.cell(0, 10, document_type, ln=True, align="C")
    pdf.ln(5)

    # Content
    pdf.set_font("Times", size=11)

    for line in document_text.splitlines():
        if line.strip():
            pdf.multi_cell(0, 7, line)
        else:
            pdf.ln(4)

    # Footer
    pdf.set_y(-15)
    pdf.set_font("Times", size=8)
    pdf.cell(
        0,
        10,
        "Generated by LegalEase AI - Review by a qualified legal professional.",
        align="C",
    )

    # Return PDF bytes
    pdf_bytes = pdf.output()

    if isinstance(pdf_bytes, bytes):
        return pdf_bytes

    return bytes(pdf_bytes)